Repository SpiNNakerManchester/spinn_common, pull requests merged in 2020-11, with the labels that each got.

#44 Move to GitHub Actions
  .github/workflows/c_actions.yml
Labels: enhancement

#45 Auto-publish our documentation
  .github/workflows/publish.yml
  .travis.yml
Labels: enhancement

#46 GITHUB_BRANCH is no longer needed
  .github/workflows/c_actions.yml
Labels: minor

#47 Get arm-none-eabi-gcc via apt-get rather than using specific action
  .github/workflows/c_actions.yml
Labels: bug
